### PR TITLE
Switch from AWS CLI to Ansible Config and SNS modules

### PR DESCRIPTION
**Pull request by bretmartin**

### CODE REVIEW

**Review by msaundersh3 — COMMENTED** [review]
This may be expected, but I found that when specifying a single region on a single line (not as a single item list) it fails with an invalid endpoint (because of a newline).

```
Invalid endpoint: https://sns.us-east-2
    .amazonaws.com
```

**Comment by bretmartin** [comment]
Could you show me the exact variable setting that results in that?

**Comment by bretmartin** [comment]
Like, was it in a YAML block or anything like that? If you can show me the exact contents of the variables file, that would be great.

**Comment by msaundersh3** [comment]
Sorry, yeah, that would be helpful to include up front.

When attempting to provide a single region, this works as expected:
```
aws_config_regions:
  - us-east-2
aws_awslogs_bucket: 'h3-hbi15745-aws-config'
```

However, this fails with the above "Invalid endpoint" error:
```
aws_config_regions: 'us-east-2'
aws_awslogs_bucket: 'h3-hbi15745-aws-config'
```

**Comment by bretmartin** [comment]
Thanks. This is unrelated to any of the code in this pull request. I've opened #4 and assigned it to you to fix this. It looks like a straightforward issue to me, but let me know if you need help.

**Review by msaundersh3 — APPROVED** [review]

**Pull request merged**
